arb-dir: lib/l10n
template-arb-file: intl_en.arb
output-localization-file: app_localizations.dart

# below 2 lines are added, so flutter uses the default directory
# to generate app_localizatoins files
output-dir: .dart_tool/flutter_gen/gen_l10n
synthetic-package: true
