// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB6JBtxmdkedi-GnSKnFylZtOpUiprxc8',
    appId: '1:399106806327:web:8d766f7f219422ef02a5b2',
    messagingSenderId: '399106806327',
    projectId: 'mynotes-9b6e3',
    authDomain: 'mynotes-9b6e3.firebaseapp.com',
    storageBucket: 'mynotes-9b6e3.firebasestorage.app',
    measurementId: 'G-95LH9BSYS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPxQ1lxdj3i1QX0JwKnOGdwUNzT2noK2w',
    appId: '1:399106806327:android:5bb006007f7816b102a5b2',
    messagingSenderId: '399106806327',
    projectId: 'mynotes-9b6e3',
    storageBucket: 'mynotes-9b6e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmyteyWd5DM6gbRFsfvcln_uhlH3VXU5I',
    appId: '1:399106806327:ios:846a93478d8729f202a5b2',
    messagingSenderId: '399106806327',
    projectId: 'mynotes-9b6e3',
    storageBucket: 'mynotes-9b6e3.firebasestorage.app',
    iosBundleId: 'com.example.mynotes',
  );
}
